import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/index.module.css';
import Card from '../comp/Card';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.section1}>
          <h1 className={styles.maintitle}>
            Get Daily Affirmations, <br /> Get Inspired!
          </h1>
          <Image
          src='/assets/positive-vibes.svg'
          layout='fixed'
          priority
          width={100}
          height={90}
          />
        </section>

        <section className={styles.section2}>
          <Card/>
        </section>
      </main>
  
    </div>
  )
}
